### ISSUE TITLE
Migration from Groovy to Kotlin DSL

### ISSUE THREAD

**Issue by utkarsh006** [bhoomi0104/XML-To-Compose#1]
- Migrating .gradle files to the .kts for modernization
- Kotlin is preferred over Groovy for writing Gradle scripts because Kotlin is : 
  - more readable and offers better compile-time checking and IDE support.
  - offers simplified, declarative plugin syntax.

**Comment by bhoomigadhiya** [comment]
Do you want to work on this issue? @utkarsh006

**Comment by utkarsh006** [comment]
@bhoomi0104 Yes, I want to work on this issue. Also, give the issue the label as hacktoberfest. 
https://hacktoberfest.com/participation/#maintainers

**Comment by bhoomigadhiya** [comment]
Ok All the best 👍
